sequenceDiagram
User->>UnixTaskbook Kernel: command
UnixTaskbook Kernel->>UnixTaskbook Kernel: parse command
UnixTaskbook Kernel->>UnixTaskbook Dynamic Library: dlopen
UnixTaskbook Kernel->>UnixTaskbook Kernel: check_task_lib
UnixTaskbook Dynamic Library->>UnixTaskbook Kernel: print_task_info
UnixTaskbook Kernel ->> User: Show task info
UnixTaskbook Dynamic Library->>UnixTaskbook Kernel: parse_complie_argv
UnixTaskbook Kernel->>UnixTaskbook Kernel: complie_program
UnixTaskbook Dynamic Library->>UnixTaskbook Kernel: utb_generate_task_test
UnixTaskbook Dynamic Library->>UnixTaskbook Kernel: utb_generate_task_control
UnixTaskbook Kernel->>UnixTaskbook Kernel: create_test
UnixTaskbook Dynamic Library->>UnixTaskbook Kernel: parse_execute_argv
UnixTaskbook Kernel->>UnixTaskbook Kernel: execute_program
UnixTaskbook Dynamic Library->>UnixTaskbook Kernel: utb_check_program
UnixTaskbook Kernel->>UnixTaskbook Kernel: check_program_result
UnixTaskbook Kernel->>User: Show program result