sequenceDiagram
User->>UnixTaskbook Kernal: command
UnixTaskbook Kernal->>UnixTaskbook Kernal: parse command
UnixTaskbook Kernal->>UnixTaskbook Dynamic Library: dlopen
UnixTaskbook Kernal->>UnixTaskbook Kernal: check_task_lib
UnixTaskbook Dynamic Library->>UnixTaskbook Kernal: print_task_info
UnixTaskbook Kernal ->> User: Show task info
UnixTaskbook Dynamic Library->>UnixTaskbook Kernal: parse_complie_argv
UnixTaskbook Kernal->>UnixTaskbook Kernal: complie_program
UnixTaskbook Dynamic Library->>UnixTaskbook Kernal: utb_generate_task_test
UnixTaskbook Dynamic Library->>UnixTaskbook Kernal: utb_generate_task_control
UnixTaskbook Kernal->>UnixTaskbook Kernal: create_test
UnixTaskbook Dynamic Library->>UnixTaskbook Kernal: parse_execute_argv
UnixTaskbook Kernal->>UnixTaskbook Kernal: execute_program
UnixTaskbook Dynamic Library->>UnixTaskbook Kernal: utb_check_program
UnixTaskbook Kernal->>UnixTaskbook Kernal: check_program_result
UnixTaskbook Kernal->>User: Show program result