# Generated by Django 4.0.4 on 2022-04-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
